//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidUp_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int AuctionID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string ProductImagePath { get; set; }
        public double StartingPrice { get; set; }
        public double CurrentPrice { get; set; }
        public Nullable<int> CurrentBidderID { get; set; }
        public int SellerID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public int ProductID { get; set; }
        public string AuctionStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
