//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidUp_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardID { get; set; }
        public string CardNumber { get; set; }
        public string CardHolderName { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string CVV { get; set; }
        public Nullable<int> OwnerUserID { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual User User { get; set; }
    }
}
