//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidUp_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string EventType { get; set; }
        public string Message { get; set; }
        public string DynamicData { get; set; }
    }
}
